//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banchuk3Isp11_13.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int IdAdmin { get; set; }
        public string AdminNane { get; set; }
        public string LastName { get; set; }
        public string Patronomyc { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string GenderId { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.DateTime DateOfBeginWork { get; set; }
        public decimal Salary { get; set; }
    
        public virtual Gender Gender { get; set; }
    }
}
