//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banchuk3Isp11_13.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedCart
    {
        public int IdMedCart { get; set; }
        public int IdPatient { get; set; }
        public System.DateTime DateUpdate { get; set; }
        public int OrderId { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Order Order { get; set; }
    }
}
